In [1]:
!pip install numpy
import numpy as np

## Parte 1: Creación y manipulación de arrays (30 puntos)

### Creación de un array
Para cumplir con esta parte, generé un array de 10 elementos aleatorios enteros entre 1 y 100 utilizando `np.random.randint()`. Este método permite generar números enteros en un rango especificado, en este caso entre 1 y 100. Esto nos proporciona el array de entrada para las operaciones subsecuentes.



In [2]:
array_1 = np.random.randint(1, 101, size=10)
print("Array generado:", array_1)

Array generado: [37 33 13 21 81 80  9  6 19  7]


### Reshape del array
A partir del array generado, cambié su forma para convertirlo en una matriz de 2x5 utilizando `reshape()`. Este método reorganiza los elementos sin alterarlos, ajustándolos en una estructura de filas y columnas.



In [3]:
matriz_2x5 = array_1.reshape(2, 5)
print("Matriz 2x5:\n", matriz_2x5)

Matriz 2x5:
 [[37 33 13 21 81]
 [80  9  6 19  7]]


### Indexación y slicing
Utilicé la indexación y el slicing para extraer la primera fila y la última columna de la matriz. Para la primera fila, seleccioné la fila con índice 0, y para la última columna, seleccioné todas las filas y la columna con índice -1. Este tipo de manipulación es común en NumPy para acceder a secciones específicas de una matriz.

In [4]:
primera_fila = matriz_2x5[0, :]
ultima_columna = matriz_2x5[:, -1]
print("Primera fila:", primera_fila)
print("Última columna:", ultima_columna)

Primera fila: [37 33 13 21 81]
Última columna: [81  7]


### Modificación de la matriz
Para modificar la matriz, asigné ceros a todos los elementos de la segunda fila (fila con índice 1). Este tipo de operación es útil para actualizar o resetear valores en una matriz. En este caso, toda la fila fue modificada con el valor 0.

In [5]:
matriz_2x5[1, :] = 0
print("Matriz modificada:\n", matriz_2x5)

Matriz modificada:
 [[37 33 13 21 81]
 [ 0  0  0  0  0]]


## Parte 2: Operaciones básicas con NumPy (30 puntos)

### Operaciones aritméticas
Para esta sección, generé dos arrays de 5 elementos aleatorios entre 1 y 50 usando `np.random.randint()`. Luego realicé dos operaciones: sumé los arrays con el operador `+`, y los multipliqué entre sí con el operador `*`. Estas operaciones son muy directas en NumPy y permiten trabajar con datos de manera rápida y eficiente.

In [6]:
array_a = np.random.randint(1, 51, size=5)
array_b = np.random.randint(1, 51, size=5)
suma = array_a + array_b
multiplicacion = array_a * array_b
print("Suma de los arrays:", suma)
print("Multiplicación de los arrays:", multiplicacion)

Suma de los arrays: [24 67 49 27 13]
Multiplicación de los arrays: [ 80 990 544  26  22]


### Promedio y desviación estándar
Para calcular el promedio y la desviación estándar de los resultados obtenidos en la suma y la multiplicación, utilicé `np.mean()` y `np.std()`. Estas funciones nos permiten obtener estadísticas descriptivas básicas, que son esenciales para analizar distribuciones de datos.

In [7]:
promedio_suma = np.mean(suma)
desviacion_suma = np.std(suma)
promedio_multiplicacion = np.mean(multiplicacion)
desviacion_multiplicacion = np.std(multiplicacion)
print("Promedio de la suma:", promedio_suma)
print("Desviación estándar de la suma:", desviacion_suma)
print("Promedio de la multiplicación:", promedio_multiplicacion)
print("Desviación estándar de la multiplicación:", desviacion_multiplicacion)

Promedio de la suma: 36.0
Desviación estándar de la suma: 19.411336893681487
Promedio de la multiplicación: 332.4
Desviación estándar de la multiplicación: 382.3995815897293


### Condiciones lógicas
Para esta parte, generé un array de 20 números aleatorios entre 0 y 1 con `np.random.rand()`. Luego, utilizando condiciones lógicas, reemplacé los valores menores a 0.5 con 0 y los mayores o iguales a 0.5 con 1. Esto es útil para realizar filtrados o categorizaciones basadas en rangos de valores.

In [8]:
array_condicional = np.random.rand(20)
array_condicional[array_condicional < 0.5] = 0
array_condicional[array_condicional >= 0.5] = 1
print("Array modificado con condiciones lógicas:", array_condicional)

Array modificado con condiciones lógicas: [1. 1. 0. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0.]


### Producto escalar
Para el producto escalar, creé dos matrices de 3x3 con números aleatorios entre 1 y 10 usando `np.random.randint()`. Luego, utilicé `np.dot()` para calcular el producto escalar entre ambas matrices. Esta operación es fundamental en álgebra lineal y se utiliza en muchos ámbitos como gráficos 3D, transformaciones y redes neuronales.

In [9]:
matriz1 = np.random.randint(1, 11, size=(3, 3))
matriz2 = np.random.randint(1, 11, size=(3, 3))
producto_escalar = np.dot(matriz1, matriz2)
print("Producto escalar:\n", producto_escalar)

Producto escalar:
 [[ 42 220 178]
 [ 14  80  66]
 [ 28 180 152]]


## Parte 3: Análisis de datos con NumPy (40 puntos)

### Matriz de datos
Para crear la matriz de datos, generé una matriz de 5 filas y 4 columnas con números aleatorios entre 1 y 20. Cada fila representa una persona y cada columna corresponde a una medición diferente (como altura, peso, etc.). Este tipo de matriz es útil para almacenar conjuntos de datos multivariados y se puede usar en análisis estadísticos o machine learning.


In [10]:
matriz_datos = np.random.randint(1, 21, size=(5, 4))
print("Matriz de datos:\n", matriz_datos)

Matriz de datos:
 [[ 6 17  7 15]
 [15  7 10  9]
 [ 1 18 15 17]
 [ 8  2  5  3]
 [ 7  8 16  4]]


### Estadísticas de las mediciones
Para obtener la media de cada columna, utilicé `np.mean()` con `axis=0`, lo que indica que el promedio se debe calcular a lo largo de las filas, es decir, para cada columna. Esto es útil para entender las tendencias de cada variable medida.

In [11]:
media_columnas = np.mean(matriz_datos, axis=0)
print("Media de cada columna:", media_columnas)

Media de cada columna: [ 7.4 10.4 10.6  9.6]


### Valores máximo y mínimo de cada fila
Utilicé `np.max()` y `np.min()` con `axis=1` para encontrar el valor máximo y mínimo de cada fila, que representa a cada persona. Esto puede ser útil para identificar los extremos de cada individuo en los datos registrados.

In [12]:
maximos_filas = np.max(matriz_datos, axis=1)
minimos_filas = np.min(matriz_datos, axis=1)
print("Máximos de cada fila:", maximos_filas)
print("Mínimos de cada fila:", minimos_filas)

Máximos de cada fila: [17 15 18  8 16]
Mínimos de cada fila: [6 7 1 2 4]


### Ordenamiento de las filas según la segunda columna
Finalmente, ordené las filas de la matriz según los valores de la segunda columna (representando, por ejemplo, el peso de cada persona). Utilicé `argsort()` para obtener los índices de las filas en el orden de la segunda columna y así reordenar la matriz. Esta técnica es útil cuando es necesario clasificar datos en función de una variable específica.

In [13]:
matriz_ordenada = matriz_datos[matriz_datos[:, 1].argsort()]
print("Matriz ordenada por la segunda columna:\n", matriz_ordenada)

Matriz ordenada por la segunda columna:
 [[ 8  2  5  3]
 [15  7 10  9]
 [ 7  8 16  4]
 [ 6 17  7 15]
 [ 1 18 15 17]]
